[package]
name = "ferrender"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.36.2"
egui = "0.36.2"
egui-phosphor = "0.14.0"
fr-core = { version = "0.1.0", path = "../fr-core" }
glam = "0.34.1"
rfd = "0.17.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
toml = "1.1.6"
ureq = "3.4.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2.190"

[dev-dependencies]
egui_kittest = { version = "0.36.2", features = ["wgpu", "eframe"] }
image = { version = "0.25", default-features = false, features = ["png"] }
