[package]
name = "ferrender"
version = "0.3.0-dev"
edition = "2024"

[dependencies]
eframe = "0.36.2"
egui = "0.36.2"
egui-phosphor = "0.14.0"
fr-core = { version = "0.3.0-dev", path = "../fr-core" }
glam = "0.34.1"
rfd = "0.17.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
toml = "1.1.6"
ureq = "3.4.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2.190"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.5"
objc2-app-kit = { version = "0.3.2", default-features = false, features = ["std", "NSApplication", "NSAppearance", "NSResponder"] }
objc2-foundation = { version = "0.3.2", default-features = false, features = ["std", "NSArray", "NSString", "NSAppleEventDescriptor", "NSAppleEventManager", "NSNotification", "NSURL", "NSData", "NSError"] }

[target.'cfg(target_os = "linux")'.dependencies]
async-io = "2.6.0"
futures-lite = "2.6.1"
zbus = "5.19.0"

[dev-dependencies]
egui_kittest = { version = "0.36.2", features = ["wgpu", "eframe"] }
image = { version = "0.25", default-features = false, features = ["png"] }
